services:
  - type: web
    name: smartbool-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_compuertas:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HUGGINGFACE_HUB_TOKEN
        value: ${HUGGINGFACE_HUB_TOKEN}
