services:
  - type: web
    name: smartbool-api
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_compuertas:app --host 0.0.0.0 --port 8000
    envVars:
      - key: HUGGINGFACE_HUB_TOKEN
        value: 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